POST http://localhost:3333/videos
#Metadado/configuração
Content-type: application/json 

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

# Com query parameter
GET http://localhost:3333/videos?search=node 

###

PUT http://localhost:3333/videos/f0732639-5f20-4080-8626-a74242a2e82e
#Metadado/configuração
Content-type: application/json 

{
    "title": "Video 02",
    "description": "Esse é o SEGUNDO vídeo",
    "duration": 200
}

###

DELETE http://localhost:3333/videos/a1f22587-506e-4033-a4ce-f40ab4cb37c0

